using System;
using System.Collections.Generic;

#nullable disable

namespace RESTClientIntercapVTEX.Entities
{
    public partial class Stmpdh
    {
        public string Stmpdh_Tippro { get; set; }
        public string Stmpdh_Artcod { get; set; }
        public string Stmpdh_Descrp { get; set; }
        public string Stmpdh_Pesctr { get; set; }
        public string Stmpdh_Pesuni { get; set; }
        public decimal? Stmpdh_Pesfac { get; set; }
        public decimal? Stmpdh_Pesmax { get; set; }
        public decimal? Stmpdh_Pesmin { get; set; }
        public string Stmpdh_Textos { get; set; }
        public string Stmpdh_Unimed { get; set; }
        public string Stmpdh_Unisec { get; set; }
        public string Stmpdh_Unipes { get; set; }
        public decimal? Stmpdh_Stkmin { get; set; }
        public decimal? Stmpdh_Stkmax { get; set; }
        public decimal? Stmpdh_Ptoped { get; set; }
        public decimal? Stmpdh_Lotfab { get; set; }
        public decimal? Stmpdh_Lotcpa { get; set; }
        public decimal? Stmpdh_Preref { get; set; }
        public string Stmpdh_Monref { get; set; }
        public DateTime Stmpdh_Fecref { get; set; }
        public string Stmpdh_Defser { get; set; }
        public int? Stmpdh_Lotref { get; set; }
        public string Stmpdh_Dderef { get; set; }
        public string Stmpdh_Defdes { get; set; }
        public string Stmpdh_Defenv { get; set; }
        public string Stmpdh_Defotr { get; set; }
        public string Stmpdh_Tipprq { get; set; }
        public string Stmpdh_Artcoq { get; set; }
        public string Stmpdh_Modcpt { get; set; }
        public string Stmpdh_Tipcpt { get; set; }
        public string Stmpdh_Codcpt { get; set; }
        public string Stmpdh_Artdis { get; set; }
        public string Stmpdh_Rubr01 { get; set; }
        public string Stmpdh_Rubr02 { get; set; }
        public string Stmpdh_Rubr03 { get; set; }
        public string Stmpdh_Rubr04 { get; set; }
        public string Stmpdh_Rubr05 { get; set; }
        public string Stmpdh_Rubr06 { get; set; }
        public string Stmpdh_Rubr07 { get; set; }
        public string Stmpdh_Rubr08 { get; set; }
        public string Stmpdh_Rubr09 { get; set; }
        public string Stmpdh_Rubr10 { get; set; }
        public string Stmpdh_Unifac { get; set; }
        public string Stmpdh_Unialt { get; set; }
        public string Stmpdh_Unicon { get; set; }
        public decimal? Stmpdh_Facfac { get; set; }
        public decimal? Stmpdh_Facalt { get; set; }
        public decimal? Stmpdh_Faccon { get; set; }
        public string Stmpdh_Unifco { get; set; }
        public string Stmpdh_Uniaco { get; set; }
        public string Stmpdh_Unicco { get; set; }
        public decimal? Stmpdh_Facfco { get; set; }
        public decimal? Stmpdh_Facaco { get; set; }
        public decimal? Stmpdh_Faccco { get; set; }
        public string Stmpdh_Modcpc { get; set; }
        public string Stmpdh_Tipcpc { get; set; }
        public string Stmpdh_Codcpc { get; set; }
        public decimal? Stmpdh_Tolcom { get; set; }
        public decimal? Stmpdh_Tolven { get; set; }
        public decimal? Stmpdh_Tolpro { get; set; }
        public string Stmpdh_Cuenvt { get; set; }
        public string Stmpdh_Cuenpv { get; set; }
        public decimal? Stmpdh_Prerep { get; set; }
        public string Stmpdh_Monrep { get; set; }
        public DateTime? Stmpdh_Fecrep { get; set; }
        public decimal? Stmpdh_Preuco { get; set; }
        public string Stmpdh_Monuco { get; set; }
        public DateTime? Stmpdh_Fecuco { get; set; }
        public int? Stmpdh_Lotrep { get; set; }
        public string Stmpdh_Dderep { get; set; }
        public decimal? Stmpdh_Preprd { get; set; }
        public string Stmpdh_Monprd { get; set; }
        public DateTime? Stmpdh_Fecprd { get; set; }
        public decimal? Stmpdh_Utilid { get; set; }
        public string Stmpdh_Bieuso { get; set; }
        public int? Stmpdh_Lotuco { get; set; }
        public string Stmpdh_Ddeuco { get; set; }
        public string Stmpdh_Kitsfc { get; set; }
        public string Stmpdh_Kitsco { get; set; }
        public string Stmpdh_Formfc { get; set; }
        public string Stmpdh_Formco { get; set; }
        public string Stmpdh_Edcoco { get; set; }
        public int? Stmpdh_Lotprd { get; set; }
        public string Stmpdh_Ddeprd { get; set; }
        public string Stmpdh_Edcaco { get; set; }
        public string Stmpdh_Edcofc { get; set; }
        public string Stmpdh_Edcafc { get; set; }
        public string Stmpdh_Argcos { get; set; }
        public short? Stmpdh_Cntlin { get; set; }
        public string Stmpdh_Gasimp { get; set; }
        public string Stmpdh_Metpro { get; set; }
        public string Stmpdh_Clasar { get; set; }
        public short? Stmpdh_Diaent { get; set; }
        public string Stmpdh_Simupd { get; set; }
        public string Stmpdh_Simufc { get; set; }
        public string Stmpdh_Simuco { get; set; }
        public decimal? Stmpdh_Volume { get; set; }
        public string Stmpdh_Prove1 { get; set; }
        public string Stmpdh_Prove2 { get; set; }
        public decimal? Stmpdh_Pctcfv { get; set; }
        public decimal? Stmpdh_Pctcfc { get; set; }
        public string Stmpdh_Indcod { get; set; }
        public string Stmpdh_Descar { get; set; }
        public string Stmpdh_Oleole { get; set; }
        public string Stmpdh_Bmpbmp { get; set; }
        public string Stmpdh_Tipgas { get; set; }
        public string Stmpdh_Expres { get; set; }
        public decimal? Stmpdh_Pocosto { get; set; }
        public string Stmpdh_Agrump { get; set; }
        public string Stmpdh_Codfam { get; set; }
        public string Stmpdh_Mongas { get; set; }
        public string Stmpdh_Deffec { get; set; }
        public string Stmpdh_Defatr { get; set; }
        public string Stmpdh_Defubi { get; set; }
        public string Stmpdh_Defest { get; set; }
        public decimal? Stmpdh_Prmxpr { get; set; }
        public decimal? Stmpdh_Prmipr { get; set; }
        public decimal? Stmpdh_Facsec { get; set; }
        public decimal? Stmpdh_Minsec { get; set; }
        public decimal? Stmpdh_Maxsec { get; set; }
        public string Stmpdh_Ctrlbf { get; set; }
        public decimal? Stmpdh_Porbof { get; set; }
        public string Stmpdh_Ctrlbc { get; set; }
        public decimal? Stmpdh_Porboc { get; set; }
        public string Stmpdh_Nvrpre { get; set; }
        public string Stmpdh_Codreg { get; set; }
        public decimal? Stmpdh_Refsec { get; set; }
        public string Stmpdh_Habret { get; set; }
        public decimal? Stmpdh_Tlffac { get; set; }
        public decimal? Stmpdh_Tlfalt { get; set; }
        public decimal? Stmpdh_Tlfcon { get; set; }
        public decimal? Stmpdh_Tlcfac { get; set; }
        public decimal? Stmpdh_Tlcalt { get; set; }
        public decimal? Stmpdh_Tlccon { get; set; }
        public string Stmpdh_Masclp { get; set; }
        public short? Stmpdh_Cntlic { get; set; }
        public string Stmpdh_Apltot { get; set; }
        public string Stmpdh_Codmer { get; set; }
        public string Stmpdh_Codsec { get; set; }
        public string Stmpdh_Codmtx { get; set; }
        public string Stmpdh_Observ { get; set; }
        public string Stmpdh_Nomcot { get; set; }
        public short? Stmpdh_Unimtx { get; set; }
        public string Stmpdh_Trazab { get; set; }
        public string Stmpdh_Cnmman { get; set; }
        public string Stmpdh_Habime { get; set; }
        public string Stmpdh_Estamo { get; set; }
        public string Stmpdh_Comori { get; set; }
        public string Stmpdh_Clasif { get; set; }
        public short? Stmpdh_Ultniv { get; set; }
        public string Stmpdh_Recalc { get; set; }
        public string Stmpdh_Tipfam { get; set; }
        public string Stmpdh_Artfam { get; set; }
        public string Usr_Stmpdh_Intnet { get; set; }
        public string Usr_Stmpdh_Pnuevo { get; set; }
        public string Usr_Stmpdh_Imgchi { get; set; }
        public string Usr_Stmpdh_Imggra { get; set; }
        public string Usr_Stmpdh_Import { get; set; }
        public string Usr_Stmpdh_Prdped { get; set; }
        public string Usr_Stmpdh_Archft { get; set; }
        public string Usr_Stmpdh_Nropar { get; set; }
        public decimal? Usr_Stmpdh_Porgim { get; set; }
        public decimal? Usr_Stmpdh_Cosmkt { get; set; }
        public string Usr_Stmpdh_Tipdis { get; set; }
        public string Usr_Stmpdh_Posara { get; set; }
        public string Usr_Stmpdh_Consus { get; set; }
        public string Usr_Stmpdh_Consug { get; set; }
        public string Usr_Stmpdh_Desimp { get; set; }
        public string Usr_Stmpdh_Varpre { get; set; }
        public string Usr_Stmpdh_Conapl { get; set; }
        public string Usr_Stmpdh_Conimg { get; set; }
        public string Usr_Stmpdh_Inclve { get; set; }
        public string Usr_Stmpdh_Chasin { get; set; }
        public string Usr_Stmpdh_Certif { get; set; }
        public string Usr_Stmpdh_Interv { get; set; }
        public decimal? Usr_Stmpdh_Smin40 { get; set; }
        public decimal? Usr_Stmpdh_Pddrop { get; set; }
        public decimal? Usr_Stmpdh_Iddrop { get; set; }
        public string Usr_Stmpdh_Videop { get; set; }
        public string Usr_Stmpdh_Exacsm { get; set; }
        public string Usr_Stmpdh_Convid { get; set; }
        public string Usr_Stmpdh_Limcnt { get; set; }
        public string Usr_Stmpdh_Deptos { get; set; }
        public string Usr_Stmpdh_Catego { get; set; }
        public string Usr_Stmpdh_Subcat { get; set; }
        public DateTime? Stmpdh_Fecalt { get; set; }
        public DateTime? Stmpdh_Fecmod { get; set; }
        public string Stmpdh_Userid { get; set; }
        public string Stmpdh_Ultopr { get; set; }
        public string Stmpdh_Debaja { get; set; }
        public string Stmpdh_Oalias { get; set; }
    }
}
